### ISSUE TITLE
Error Install plugin

### ISSUE THREAD

**Issue by conejodan** [Corollarium/cordova-plugin-radar#1]
I am trying to use this plugin, I install it and everything is fine, but when I open the Android Studio the following appears,

Any solution?

![image](https://user-images.githubusercontent.com/35090164/51697494-8e706c80-1fcd-11e9-8b94-6d35b2b49445.png)

**Comment by brunobg** [comment]
Sorry, we are not using this plugin anymore. Perhaps you can remove the fonts from the resource?

**Comment by conejodan** [comment]
It is bad news. I think I will try another alternative. Thank you very much for the reply
